services:
  postgres:
    image: postgres:16
    container_name: transcendence_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence_network

  backend:
    build: ./backend
    container_name: transcendence_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FRONTEND_URL: https://localhost
      FORTY_TWO_CALLBACK_URL: https://localhost/api/auth/42/callback
      CORS_ORIGINS: https://localhost,http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      - postgres
    expose:
      - "3000"
    networks:
      - transcendence_network

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - transcendence_network

  nginx:
    build: ./nginx
    container_name: transcendence_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence_network

volumes:
  postgres_data:
  uploads:

networks:
  transcendence_network:
    driver: bridge
